### ISSUE TITLE
Samples are not working on Firefox (SystemJS loads app from https://registry.jspm.io/app.js)

### ISSUE THREAD

**Issue by JohannesHoppe** [Angular2Buch/code#2]
GET https://registry.jspm.io/app.js

404 Not Found
        1,14s  
es6-mod...16.6.js (Zeile 1)
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function

function onGlobalPostMessage(event) {

angular2.dev.js (Zeile 2788, Spalte 17)
"NetworkError: 404 Not Found - https://registry.jspm.io/app.js"
app.js
Potentially unhandled rejection [3] Error loading "app" at https://registry.jspm.io/app.js
Not Found: https://registry.jspm.io/app.js (WARNING: non-Error used)

es6-mod...16.6.js (Zeile 1)

**Comment by JohannesHoppe** [comment]
should work as soon as angular includes patch from that issue:  
https://github (dot) com/angular/angular.io/issues/69

**Comment by JohannesHoppe** [comment]
firefox + alpha-35 == <3

**Comment by tabinnorway** [comment]
This works in alpha-28, alpha-35 but is broken again in alpha-37
