### ISSUE TITLE
[reddit-clone] Artikel nach ratings sortieren

### ISSUE THREAD

**Issue by GregOnNet** [Angular2Buch/code#3]

**Comment by JohannesHoppe** [comment]
FYI, there is no (and won't be ever) an orderBy pipe inside angular core!
see https://github (dot) com/angular/angular/pull/2956

conclusion: list must be sorted in code

**Comment by JohannesHoppe** [comment]
see also
https://github (dot) com/angular/angular/issues/2340

(== me complaining)
