### ISSUE TITLE
Adding an item to shopping list won't work

### ISSUE THREAD

**Issue by d-koppenhagen** [Angular2Buch/code#4]
Hey I added a [shopping list application](https://angular2buch.de/code/shopping-list/) to our Angular 2 playground page.
Unfortunately I've some trouble by adding new Items to the list. On adding an item the input is `undefined` (logged [here](https://github.com/Angular2Buch/code/blob/gh-pages/shopping-list/app.ts#L68)).

[main.html](https://github.com/Angular2Buch/code/blob/gh-pages/shopping-list/templates/main.html#L10L19)

```
<input #inputName />
<input #inputQuantity />
<button (click)="addItem(inputName, inputQuantity)"></button>
```

[app.ts](https://github.com/Angular2Buch/code/blob/gh-pages/shopping-list/app.ts#L66L72)

```
addItem(name: String, quantity: String) {
    console.log(name, quantity);
    this.items.push(new Item(name, quantity, false));
    name = null;
    quantity  = null;
}
```

any suggestions for solving this problem @GregOnNet @JohannesHoppe ?
Thanks ;-)

**Comment by JohannesHoppe** [comment]
btw, your code is heavily missing underscore! ;-)

... i can investigate on this in the evening.

**Comment by GregOnNet** [comment]
@JohannesHoppe What do you mean with 

> btw, your code is heavily missing underscore! ;-)

**Comment by d-koppenhagen** [comment]
+1

**Comment by JohannesHoppe** [comment]
@GregOnNet siehe meinen letzten Commit.
Underscore (bzw. lodash) kombiniert mit Array-Functions: sexxxey :sunglasses:

``` javascript
// vorher
deleteChecked() {
  for (var i=this.items.length-1; i>=0; i--){
    if (this.items[i].checked)
      this.items.splice(i, 1);
  }
}
```

``` javascript
// nachher
deleteChecked() {
  _.remove(this.items, (item) => item.checked);
}
```

**Comment by GregOnNet** [comment]
Ich sehe was du meinst.
Ich weiß noch nicht, ob es im Kontext des Buches gut ist, eine weitere Abhängigkeit reinzupringen.

Ich würde versuchen natives JS zu schreiben.
Ggf. könnten wir die for-Schleife in eine .map()-Funktion refaktorisieren.

``` js
deleteChecked() {
  this.items = this.items.map( (item) => { 
     if(item.checked) return item;
  });
}
```

**Comment by GregOnNet** [comment]
filter ist eventuell besser.

``` js
deleteChecked() {
  this.items = this.items.filter( (item) => { 
     return item.checked;
  });
}
```

_Nachteil_
map und filter erzeugen neue listen. Kann sein, dass das Angular veranlasst das gesammte DOM neu zu rendern.

**Comment by GregOnNet** [comment]
Ok, lodash produziert intern auch eine neue Instanz eines Arrays: https://github.com/lodash/lodash/blob/master/lodash.js#L4892

**Comment by JohannesHoppe** [comment]
Hmmm.... ok. Da habe ich gar nicht wirklich drüber nachgedacht.
Ich denke lodash/underscore ist ein de-facto Standard:
![lodash](https://cloud.githubusercontent.com/assets/640639/9194138/5163c8b0-4019-11e5-991c-95ffbb833b0e.png)
[Quelle](https://david-dm.org/)

Aber du hast recht, da muss man drüber reden.
Gleich ES6+ features wie `map` und `for-of` einzusetzen ist natürlich noch cooler.

Die Frage, was Angular mit dem neuen Array macht, sollten wir uns merken.

**Comment by JohannesHoppe** [comment]
NEU:
1. Two-way Data Binding via <input [(ng-model)]="name">
2. Bubbling click if with (^click), since clicking child elements won’t trigger the event handler
