### ISSUE TITLE
JSPM: GitHub rate limit reached.

### ISSUE THREAD

**Issue by JohannesHoppe** [Angular2Buch/code#5]
https://travis-ci.org/Angular2Buch/code/builds/76865288

```
warn GitHub rate limit reached.

[...]

warn Timed out on getPackageConfig for github:jspm/nodelibs-fs, retrying (1).
     Set the timeout via jspm config registries.github.timeouts.getPackageConfig <secs>

[...]

The command "jspm install" failed and exited with 1 during .
```

**Comment by JohannesHoppe** [comment]
Lösung:

https://github.com/jspm/github/issues/20
https://github.com/jspm/jspm-cli/wiki/Endpoints/d7b27fc88d741a20fafad6fd99474a167d9f66cb#travis-ci

**Comment by JohannesHoppe** [comment]
Der hier war geschummelt:
https://github.com/Angular2Buch/code-public/commit/f3c391c861a8c9a6760e4e3e00df3096ebfec8cf

Sieht man daran, dass keine Links zum Commit und zum Travis-Build dabei sind.

**Comment by JohannesHoppe** [comment]
NEW `jspm registry export github`, which was a 0.15 breaking change.

https://github.com/jspm/jspm-cli/wiki/Registries

**Comment by GregOnNet** [comment]
Oha, der Rob Eisenberg hat da auch seine Finger im Spiel...

Also das Problem war, dass das Skript auf die Eingabe der Credentials gewartet hat, richtig?

**Comment by JohannesHoppe** [comment]
Exakt, in der lokalen Shell kann man dann Username + Passwort oder Token eingeben und es läuft einfach weiter. JSPM merkt sich die Daten auch fürs nächste mal. Für Travis geht das natürlich nicht, daher muss man vorab die Credentials vom Buildbot hinterlegen. Dann sollte es klappen.

Jop, Rob Eisenberg mischt auch an der JSPM / System.js Sache herum. Ein gescheites Modul-Management brauch er ebenso für aurelia.

**Comment by JohannesHoppe** [comment]
fixed in https://github.com/Angular2Buch/code/commit/cd99f4cb2500fbcfec6a8e45b2f0ea740b926bae

**Comment by JohannesHoppe** [comment]
The token must have the scope: "public_repo "
(Scopes limit access for personal tokens)
